"""change location_id to city_id in registers table

Revision ID: 18eb2e7d544b
Revises: 38228dffeeaa
Create Date: 2014-10-27 15:12:20.663498

"""

# revision identifiers, used by Alembic.
revision = '18eb2e7d544b'
down_revision = '38228dffeeaa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registers', sa.Column('city_id', sa.Integer(), nullable=False))
    op.drop_column('registers', 'location_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registers', sa.Column('location_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('registers', 'city_id')
    ### end Alembic commands ###
