"""fisrt edition

Revision ID: 1a3768570587
Revises: None
Create Date: 2014-10-24 22:03:19.118542

"""

# revision identifiers, used by Alembic.
revision = '1a3768570587'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.Unicode(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=48), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('is_email_confirmed', sa.BOOLEAN(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('identity', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.Column('body', sa.Unicode(length=420), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('is_disabled', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Unicode(length=18), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('name', sa.Unicode(length=48), nullable=False),
    sa.Column('need', sa.Unicode(length=18), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=18), nullable=False),
    sa.Column('age', sa.Unicode(length=30), nullable=False),
    sa.Column('sex', sa.BOOLEAN(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Unicode(length=120), nullable=False),
    sa.Column('campus', sa.Unicode(length=60), nullable=False),
    sa.Column('remark', sa.Unicode(length=300), nullable=False),
    sa.Column('is_canceled', sa.BOOLEAN(), nullable=False),
    sa.Column('is_submitted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property', sa.Unicode(length=18), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.SMALLINT(), nullable=False),
    sa.Column('body', sa.Unicode(length=420), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('is_disabled', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profession', sa.Unicode(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Unicode(length=18), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.SMALLINT(), nullable=False),
    sa.Column('body', sa.Unicode(length=420), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('is_disabled', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('district', sa.Unicode(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=90), nullable=False),
    sa.Column('age_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('intro', sa.Unicode(length=420), nullable=False),
    sa.Column('photo', sa.CHAR(length=36), nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), nullable=False),
    sa.Column('page_view', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=18), nullable=False),
    sa.Column('age', sa.Unicode(length=30), nullable=False),
    sa.Column('sex', sa.BOOLEAN(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Unicode(length=120), nullable=False),
    sa.Column('remark', sa.Unicode(length=300), nullable=False),
    sa.Column('is_canceled', sa.BOOLEAN(), nullable=False),
    sa.Column('is_submitted', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Unicode(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mobile', sa.CHAR(length=11), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=90), nullable=False),
    sa.Column('slogan', sa.Unicode(length=90), nullable=False),
    sa.Column('contact', sa.Unicode(length=18), nullable=False),
    sa.Column('address', sa.Unicode(length=120), nullable=False),
    sa.Column('authorization', sa.CHAR(length=36), nullable=False),
    sa.Column('photo', sa.CHAR(length=36), nullable=False),
    sa.Column('logo', sa.CHAR(length=36), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('is_confirmed', sa.BOOLEAN(), nullable=False),
    sa.Column('intro', sa.Unicode(length=420), nullable=False),
    sa.Column('traffic', sa.Unicode(length=90), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('page_view', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Unicode(length=18), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=90), nullable=False),
    sa.Column('age_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('consult_time', sa.Unicode(length=60), nullable=False),
    sa.Column('is_tastable', sa.BOOLEAN(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('is_round', sa.BOOLEAN(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('intro', sa.Unicode(length=420), nullable=False),
    sa.Column('is_closed', sa.BOOLEAN(), nullable=False),
    sa.Column('page_view', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.SMALLINT(), nullable=False),
    sa.Column('body', sa.Unicode(length=420), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('is_disabled', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_comments')
    op.drop_table('classes')
    op.drop_table('types')
    op.drop_table('organizations')
    op.drop_table('ages')
    op.drop_table('activity_orders')
    op.drop_table('activities')
    op.drop_table('locations')
    op.drop_table('classes_comments')
    op.drop_table('times')
    op.drop_table('professions')
    op.drop_table('organization_comments')
    op.drop_table('properties')
    op.drop_table('class_orders')
    op.drop_table('registers')
    op.drop_table('sizes')
    op.drop_table('site_comments')
    op.drop_table('users')
    op.drop_table('class_time')
    op.drop_table('cities')
    ### end Alembic commands ###
