"""update

Revision ID: 23bfadeb2497
Revises: 31886214ea07
Create Date: 2014-10-19 15:57:26.983810

"""

# revision identifiers, used by Alembic.
revision = '23bfadeb2497'
down_revision = '31886214ea07'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ages', sa.Column('age', sa.Unicode(length=16), nullable=True))
    op.drop_column('ages', 'time')
    op.add_column('professions', sa.Column('profession', sa.Unicode(length=16), nullable=True))
    op.drop_column('professions', 'time')
    op.add_column('properties', sa.Column('property', sa.Unicode(length=16), nullable=True))
    op.drop_column('properties', 'time')
    op.add_column('sizes', sa.Column('size', sa.Unicode(length=16), nullable=True))
    op.drop_column('sizes', 'time')
    op.add_column('types', sa.Column('type', sa.Unicode(length=16), nullable=True))
    op.drop_column('types', 'time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('types', sa.Column('time', mysql.VARCHAR(length=16), nullable=True))
    op.drop_column('types', 'type')
    op.add_column('sizes', sa.Column('time', mysql.VARCHAR(length=16), nullable=True))
    op.drop_column('sizes', 'size')
    op.add_column('properties', sa.Column('time', mysql.VARCHAR(length=16), nullable=True))
    op.drop_column('properties', 'property')
    op.add_column('professions', sa.Column('time', mysql.VARCHAR(length=16), nullable=True))
    op.drop_column('professions', 'profession')
    op.add_column('ages', sa.Column('time', mysql.VARCHAR(length=16), nullable=True))
    op.drop_column('ages', 'age')
    ### end Alembic commands ###
