"""add source and organization_id for charline

Revision ID: 2a0fc4f10e29
Revises: 5aeff456b072
Create Date: 2014-11-06 20:11:25.133210

"""

# revision identifiers, used by Alembic.
revision = '2a0fc4f10e29'
down_revision = '5aeff456b072'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_lines', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('chat_lines', sa.Column('source', sa.Integer(), nullable=False))
    op.alter_column('organizations', 'site',
               existing_type=mysql.CHAR(length=36),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'site',
               existing_type=mysql.CHAR(length=36),
               nullable=True)
    op.drop_column('chat_lines', 'source')
    op.drop_column('chat_lines', 'organization_id')
    ### end Alembic commands ###
