"""remove time column in activity_order

Revision ID: 38228dffeeaa
Revises: 1a3768570587
Create Date: 2014-10-26 13:59:36.735148

"""

# revision identifiers, used by Alembic.
revision = '38228dffeeaa'
down_revision = '1a3768570587'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_orders', 'time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_orders', sa.Column('time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    ### end Alembic commands ###
