"""add star

Revision ID: 44a44f522dc
Revises: fcdcba3f04b
Create Date: 2014-11-09 15:33:43.069873

"""

# revision identifiers, used by Alembic.
revision = '44a44f522dc'
down_revision = 'fcdcba3f04b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('star', sa.Float(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'star')
    ### end Alembic commands ###
