"""add chat tables

Revision ID: 4dbff992429
Revises: 18eb2e7d544b
Create Date: 2014-11-01 23:57:04.843730

"""

# revision identifiers, used by Alembic.
revision = '4dbff992429'
down_revision = '18eb2e7d544b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unified_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mobile_key', sa.CHAR(length=64), nullable=False),
    sa.Column('web_key', sa.CHAR(length=32), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unified_id', sa.Integer(), nullable=False),
    sa.Column('is_user', sa.BOOLEAN(), nullable=False),
    sa.Column('content', sa.Unicode(length=500), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_lines')
    op.drop_table('unified_id')
    ### end Alembic commands ###
