"""add location_id

Revision ID: 5060216c3a17
Revises: 2a0fc4f10e29
Create Date: 2014-11-06 21:44:41.625385

"""

# revision identifiers, used by Alembic.
revision = '5060216c3a17'
down_revision = '2a0fc4f10e29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('location_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'location_id')
    ### end Alembic commands ###
