"""add slogan

Revision ID: 54bc1b51c815
Revises: 1b9c3e4609b0
Create Date: 2014-10-23 16:30:26.129779

"""

# revision identifiers, used by Alembic.
revision = '54bc1b51c815'
down_revision = '1b9c3e4609b0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('slogan', sa.Unicode(length=256), nullable=True))
    op.drop_column('users', 'last_login')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('organizations', 'slogan')
    ### end Alembic commands ###
