"""add source_sit_id confirmed_time

Revision ID: 55b4619add57
Revises: 553b20e5a65a
Create Date: 2014-11-13 15:36:13.006009

"""

# revision identifiers, used by Alembic.
revision = '55b4619add57'
down_revision = '553b20e5a65a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('confirmed_time', sa.Integer(), nullable=False))
    op.add_column('organizations', sa.Column('source_site_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'source_site_id')
    op.drop_column('organizations', 'confirmed_time')
    ### end Alembic commands ###
