"""remote age_id

Revision ID: 5aeff456b072
Revises: 21587d00e411
Create Date: 2014-11-04 23:57:24.312730

"""

# revision identifiers, used by Alembic.
revision = '5aeff456b072'
down_revision = '21587d00e411'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classes', 'age_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('age_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    ### end Alembic commands ###
