"""add name for recommended activity

Revision ID: 8295fb71cec
Revises: 1318630d566a
Create Date: 2014-11-15 17:55:35.521532

"""

# revision identifiers, used by Alembic.
revision = '8295fb71cec'
down_revision = '1318630d566a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommended_activity', sa.Column('name', sa.String(length=50), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommended_activity', 'name')
    ### end Alembic commands ###
