"""empty message

Revision ID: f888c51035f
Revises: fcdcba3f04b
Create Date: 2014-11-09 13:19:12.691061

"""

# revision identifiers, used by Alembic.
revision = 'f888c51035f'
down_revision = 'fcdcba3f04b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province', sa.Unicode(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province')
    )
    op.add_column(u'cities', sa.Column('province_id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'cities', 'province_id')
    op.drop_table('provinces')
    ### end Alembic commands ###
